/* Generated By:JJTree: Do not edit this line. JavaParserTreeConstants.java */

package jp.ac.ritsumei.cs.fse.jrt.parser;

public interface JavaParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTPACKAGEDECLARATION = 1;
  public int JJTIMPORTDECLARATION = 2;
  public int JJTTYPEDECLARATION = 3;
  public int JJTCLASSDECLARATION = 4;
  public int JJTUNMODIFIEDCLASSDECLARATION = 5;
  public int JJTCLASSBODY = 6;
  public int JJTNESTEDCLASSDECLARATION = 7;
  public int JJTCLASSBODYDECLARATION = 8;
  public int JJTMETHODDECLARATIONLOOKAHEAD = 9;
  public int JJTINTERFACEDECLARATION = 10;
  public int JJTNESTEDINTERFACEDECLARATION = 11;
  public int JJTUNMODIFIEDINTERFACEDECLARATION = 12;
  public int JJTINTERFACEMEMBERDECLARATION = 13;
  public int JJTFIELDDECLARATION = 14;
  public int JJTVARIABLEDECLARATOR = 15;
  public int JJTVARIABLEDECLARATORID = 16;
  public int JJTVARIABLEINITIALIZER = 17;
  public int JJTARRAYINITIALIZER = 18;
  public int JJTMETHODDECLARATION = 19;
  public int JJTMETHODDECLARATOR = 20;
  public int JJTFORMALPARAMETERS = 21;
  public int JJTFORMALPARAMETER = 22;
  public int JJTCONSTRUCTORDECLARATION = 23;
  public int JJTEXPLICITCONSTRUCTORINVOCATION = 24;
  public int JJTINITIALIZER = 25;
  public int JJTTYPE = 26;
  public int JJTPRIMITIVETYPE = 27;
  public int JJTRESULTTYPE = 28;
  public int JJTNAME = 29;
  public int JJTNAMELIST = 30;
  public int JJTEXPRESSION = 31;
  public int JJTASSIGNMENTOPERATOR = 32;
  public int JJTCONDITIONALEXPRESSION = 33;
  public int JJTCONDITIONALOREXPRESSION = 34;
  public int JJTCONDITIONALANDEXPRESSION = 35;
  public int JJTINCLUSIVEOREXPRESSION = 36;
  public int JJTEXCLUSIVEOREXPRESSION = 37;
  public int JJTANDEXPRESSION = 38;
  public int JJTEQUALITYEXPRESSION = 39;
  public int JJTINSTANCEOFEXPRESSION = 40;
  public int JJTRELATIONALEXPRESSION = 41;
  public int JJTSHIFTEXPRESSION = 42;
  public int JJTADDITIVEEXPRESSION = 43;
  public int JJTMULTIPLICATIVEEXPRESSION = 44;
  public int JJTUNARYEXPRESSION = 45;
  public int JJTPREINCREMENTEXPRESSION = 46;
  public int JJTPREDECREMENTEXPRESSION = 47;
  public int JJTUNARYEXPRESSIONNOTPLUSMINUS = 48;
  public int JJTCASTLOOKAHEAD = 49;
  public int JJTPOSTFIXEXPRESSION = 50;
  public int JJTCASTEXPRESSION = 51;
  public int JJTPRIMARYEXPRESSION = 52;
  public int JJTPRIMARYPREFIX = 53;
  public int JJTPRIMARYSUFFIX = 54;
  public int JJTRESPONSIVENAME = 55;
  public int JJTLITERAL = 56;
  public int JJTBOOLEANLITERAL = 57;
  public int JJTNULLLITERAL = 58;
  public int JJTARGUMENTS = 59;
  public int JJTARGUMENTLIST = 60;
  public int JJTALLOCATIONEXPRESSION = 61;
  public int JJTARRAYDIMSANDINITS = 62;
  public int JJTSTATEMENT = 63;
  public int JJTLABELEDSTATEMENT = 64;
  public int JJTBLOCK = 65;
  public int JJTBLOCKSTATEMENT = 66;
  public int JJTLOCALVARIABLEDECLARATION = 67;
  public int JJTEMPTYSTATEMENT = 68;
  public int JJTSTATEMENTEXPRESSION = 69;
  public int JJTSWITCHSTATEMENT = 70;
  public int JJTSWITCHLABEL = 71;
  public int JJTIFSTATEMENT = 72;
  public int JJTWHILESTATEMENT = 73;
  public int JJTDOSTATEMENT = 74;
  public int JJTFORSTATEMENT = 75;
  public int JJTFORINIT = 76;
  public int JJTSTATEMENTEXPRESSIONLIST = 77;
  public int JJTFORUPDATE = 78;
  public int JJTBREAKSTATEMENT = 79;
  public int JJTCONTINUESTATEMENT = 80;
  public int JJTRETURNSTATEMENT = 81;
  public int JJTTHROWSTATEMENT = 82;
  public int JJTSYNCHRONIZEDSTATEMENT = 83;
  public int JJTTRYSTATEMENT = 84;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "PackageDeclaration",
    "ImportDeclaration",
    "TypeDeclaration",
    "ClassDeclaration",
    "UnmodifiedClassDeclaration",
    "ClassBody",
    "NestedClassDeclaration",
    "ClassBodyDeclaration",
    "MethodDeclarationLookahead",
    "InterfaceDeclaration",
    "NestedInterfaceDeclaration",
    "UnmodifiedInterfaceDeclaration",
    "InterfaceMemberDeclaration",
    "FieldDeclaration",
    "VariableDeclarator",
    "VariableDeclaratorId",
    "VariableInitializer",
    "ArrayInitializer",
    "MethodDeclaration",
    "MethodDeclarator",
    "FormalParameters",
    "FormalParameter",
    "ConstructorDeclaration",
    "ExplicitConstructorInvocation",
    "Initializer",
    "Type",
    "PrimitiveType",
    "ResultType",
    "Name",
    "NameList",
    "Expression",
    "AssignmentOperator",
    "ConditionalExpression",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "InclusiveOrExpression",
    "ExclusiveOrExpression",
    "AndExpression",
    "EqualityExpression",
    "InstanceOfExpression",
    "RelationalExpression",
    "ShiftExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "PreIncrementExpression",
    "PreDecrementExpression",
    "UnaryExpressionNotPlusMinus",
    "CastLookahead",
    "PostfixExpression",
    "CastExpression",
    "PrimaryExpression",
    "PrimaryPrefix",
    "PrimarySuffix",
    "ResponsiveName",
    "Literal",
    "BooleanLiteral",
    "NullLiteral",
    "Arguments",
    "ArgumentList",
    "AllocationExpression",
    "ArrayDimsAndInits",
    "Statement",
    "LabeledStatement",
    "Block",
    "BlockStatement",
    "LocalVariableDeclaration",
    "EmptyStatement",
    "StatementExpression",
    "SwitchStatement",
    "SwitchLabel",
    "IfStatement",
    "WhileStatement",
    "DoStatement",
    "ForStatement",
    "ForInit",
    "StatementExpressionList",
    "ForUpdate",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "ThrowStatement",
    "SynchronizedStatement",
    "TryStatement",
  };
}
