/*
 *     ASTClassBody.java  Aug 24, 2001
 *
 *     Katsuhisa Maruyama (maru@fse.jrt.cs.ritsumei.ac.jp)
 */

/* Generated By:JJTree: Do not edit this line. ASTClassBody.java */

package jp.ac.ritsumei.cs.fse.jrt.parser.ast;
import jp.ac.ritsumei.cs.fse.jrt.parser.*;
import jp.ac.ritsumei.cs.fse.jrt.model.JavaClass;
import jp.ac.ritsumei.cs.fse.jrt.model.JavaMethod;
import jp.ac.ritsumei.cs.fse.jrt.model.JavaStatement;

public class ASTClassBody extends SimpleNode {
    private JavaClass jclass = new JavaClass(this);

    public ASTClassBody(int id) {
        super(id);
    }

    public ASTClassBody(JavaParser p, int id) {
        super(p, id);
    }

    public JavaClass getJavaClass() {
        return jclass;
    }

    public void voidJavaClass() {
        jclass = null;
    }

    public boolean isVoid() {
        if (jclass == null) {
            return true;
        }
        return false;
    }

    public void setName(String name) {
        jclass.setName(name);
    }
 
    public void addJavaMethod(JavaMethod jmethod) {
        jclass.addJavaMethod(jmethod);
    }

    public void addJavaField(JavaStatement jst) {
        jclass.addJavaField(jst);
    }

    public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
