/*
 *     ASTContinueStatement.java  Aug 31, 2001
 *
 *     Katsuhisa Maruyama (maru@fse.jrt.cs.ritsumei.ac.jp)
 */

/* Generated By:JJTree: Do not edit this line. ASTContinueStatement.java */

package jp.ac.ritsumei.cs.fse.jrt.parser.ast;
import jp.ac.ritsumei.cs.fse.jrt.parser.*;
import jp.ac.ritsumei.cs.fse.jrt.model.JavaStatement;

public class ASTContinueStatement extends SimpleNode {
    private JavaStatement jstatement = new JavaStatement(this);
    private String name = null;

    public ASTContinueStatement(int id) {
        super(id);
    }

    public ASTContinueStatement(JavaParser p, int id) {
        super(p, id);
    }

    public JavaStatement getJavaStatement() {
        return jstatement;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setResponsive(Token token) {
        jstatement.setResponsive(token.beginLine, token.beginColumn,
                                 token.endLine, token.endColumn);
    }

    public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
