/*
 *     ASTConstructorDeclaration.java  Aug 29, 2001
 *
 *     Katsuhisa Maruyama (maru@fse.jrt.cs.ritsumei.ac.jp)
 */

/* Generated By:JJTree: Do not edit this line. ASTConstructorDeclaration.java */

package jp.ac.ritsumei.cs.fse.jrt.parser.ast;
import jp.ac.ritsumei.cs.fse.jrt.parser.*;
import jp.ac.ritsumei.cs.fse.jrt.model.JavaClass;
import jp.ac.ritsumei.cs.fse.jrt.model.JavaMethod;
import jp.ac.ritsumei.cs.fse.jrt.model.JavaStatement;
import jp.ac.ritsumei.cs.fse.jrt.model.JavaModifier;

public class ASTConstructorDeclaration extends SimpleNode {
    private JavaMethod jmethod = new JavaMethod(this);

    public ASTConstructorDeclaration(int id) {
        super(id);
    }

    public ASTConstructorDeclaration(JavaParser p, int id) {
        super(p, id);
    }

    public JavaMethod getJavaMethod() {
        return jmethod;
    }

    public void setName(String name) {
        jmethod.setName(name);
    }

    public void setModifier(JavaModifier modifier) {
        jmethod.setModifier(modifier);
    }

    public void setType(String type) {
        jmethod.setType(type);
    }

    public void setJavaClass(JavaClass jclass) {
        jmethod.setJavaClass(jclass);
    }

    public void setResponsive(Token token) {
        jmethod.setResponsive(token.beginLine, token.beginColumn,
                              token.endLine, token.endColumn);
    }

    public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
