/*
 *     ASTMethodDeclarator.java  Aug 31, 2001
 *
 *     Katsuhisa Maruyama (maru@fse.jrt.cs.ritsumei.ac.jp)
 */

/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarator.java */

package jp.ac.ritsumei.cs.fse.jrt.parser.ast;
import jp.ac.ritsumei.cs.fse.jrt.parser.*;
import jp.ac.ritsumei.cs.fse.jrt.model.JavaMethod;

public class ASTMethodDeclarator extends SimpleNode {
    private JavaMethod jmethod = new JavaMethod(this);

    public ASTMethodDeclarator(int id) {
        super(id);
    }

    public ASTMethodDeclarator(JavaParser p, int id) {
        super(p, id);
    }

    public JavaMethod getJavaMethod() {
        return jmethod;
    }

    public void setResponsive(Token token) {
        jmethod.setResponsive(token.beginLine, token.beginColumn,
                              token.endLine, token.endColumn);
    }

    public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
