/*
 *     ASTSwitchLabel.java  Aug 30, 2001
 *
 *     Katsuhisa Maruyama (maru@fse.jrt.cs.ritsumei.ac.jp)
 */

/* Generated By:JJTree: Do not edit this line. ASTSwitchLabel.java */

package jp.ac.ritsumei.cs.fse.jrt.parser.ast;
import jp.ac.ritsumei.cs.fse.jrt.parser.*;
import jp.ac.ritsumei.cs.fse.jrt.model.JavaStatement;

public class ASTSwitchLabel extends SimpleNode {
    private JavaStatement jstatement = new JavaStatement(this);
    private boolean defaultLabel = false;
    private String name;

    public ASTSwitchLabel(int id) {
        super(id);
    }

    public ASTSwitchLabel(JavaParser p, int id) {
        super(p, id);
    }

    public JavaStatement getJavaStatement() {
        return jstatement;
    }

    public void setLabel(String name) {
        this.name = name;
    }

    public String getLabel() {
        return name;
    }

    public void setDefaultLabel(boolean bool) {
        defaultLabel = bool;
    }

    public boolean isDefaultLabel() {
        return defaultLabel;
    }

    public Object jjtAccept(JavaParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
